package com.codingpixel.healingbudz.network.model;

public class URL {
    // 139.162.37.73http://139.162.37.73/healingbudz_live/
    // 138.68.229.113
//    public static final String IP_SERVER = "139.162.37.73";
//        public static final String IP_SERVER = "healingbudz.codingpixel.co";
//    public static final String IP_SERVER = "healingbudz.cannablazeed.com";
    public static final String IP_SERVER = "healingbudz.com";
//        public static final String PROJECT_NAME = "healingbudz_live";
//    public static final String PROJECT_NAME = "healingbudz";
//    public static final String sharedBaseUrl = "http://" + IP_SERVER + "/" + PROJECT_NAME;
    public static final String sharedBaseUrl = "https://" + IP_SERVER;//+ "/" + PROJECT_NAME;
    //    public static String getLocatioZipcode_part1 = "https://maps.google.com/maps/api/geocode/json?key=AIzaSyAfFBUJJB6b40QkWOmlkCOCJGxWeU29hbE&&components=country%3a";
    public static String getLocatioZipcode_part1 = "https://maps.google.com/maps/api/geocode/json?key=AIzaSyCiDgdLD46NLVGAV3AKcEZt4DKTtCeprQE&&components=country%3a";
    public static String getLocatioZipcode_part2 = "%7Cpostal_code:";
    public static String getLocatioZipcode_part3 = "&sensor=true";
    //        public static String baseurl = "http://" + IP_SERVER + "/" + PROJECT_NAME + "/api/v1/";
    public static String baseurl = "https://" + IP_SERVER + "/api/v1/";
    public static String check_special_email = "check_special_email";
    //        public static String images_baseurl = "http://" + IP_SERVER + "/" + PROJECT_NAME + "/public/images";
    public static String images_baseurl = "https://" + IP_SERVER + "/public/images";
    //        public static String videos_baseurl = "http://" + IP_SERVER + "/" + PROJECT_NAME + "/public/videos";
    public static String videos_baseurl = "https://" + IP_SERVER + "/public/videos";

    public static String socket_url = "https://" + IP_SERVER + ":3000/";

    public static String getPostUrl(int postId) {
        return "Hey Bud! Check out the Healing Budz app for your smart phone.” Download it today from  https://" + IP_SERVER + "/get-post/" + postId;
    }

    //        public static String getPostUrl(int postId) {
//        return "Hey Bud! Check out the Healing Budz app for your smart phone.” Download it today from  https://" + IP_SERVER + PROJECT_NAME + "/get-post/" + postId;
//    }
//    public static String socket_url = "http://139.162.37.73:3000/";
    public static String check_email_availablity = "check_email";
    public static String forget_password = baseurl + "forget_password";
    public static String reset_password = baseurl + "update_password";
    public static String get_defaults = baseurl + "get_defaults";
    public static String add_hb_media = baseurl + "add_hb_media";
    public static String register = baseurl + "register";
    public static String login = baseurl + "login";
    public static String update_subscription = baseurl + "update_subscription";
    public static String get_keywords = baseurl + "get_keywords";
    public static String delete_subscription = baseurl + "delete_subscription";
    public static String social_login = baseurl + "social_login";
    public static String refresh_user_data = baseurl + "get_user_session";
    public static String update_pop_up = baseurl + "update_pop_up";
    public static String globle_search = baseurl + "globle_search";
    public static String upload_profile_img = baseurl + "add_image_profile";
    public static String upload_strain_image = baseurl + "upload_strain_image";
    public static String get_expertise = baseurl + "get_expertise";
    public static String add_expertise = baseurl + "add_expertise";
    public static String add_question = baseurl + "add_question";
    public static String get_activities = baseurl + "get_activities";
    public static String filter_activity = baseurl + "filter_activity";
    public static String get_questions = baseurl + "get_questions";
    public static String get_question = baseurl + "get_question";
    public static String offline_user = baseurl + "offline_user";
    public static String get_answer_question = baseurl + "get_answer_question";
    public static String get_answers = baseurl + "get_answers";
    public static String get_answer = baseurl + "get_answer";
    public static String add_answer = baseurl + "add_answer";
    public static String add_image = baseurl + "add_image";
    public static String update_image = baseurl + "update_image";
    public static String update_cover = baseurl + "update_cover";
    public static String update_cover_orignal_image = baseurl + "update_cover_orignal_image";
    public static String add_video = baseurl + "add_video";
    public static String update_avatar = baseurl + "update_avatar";
    public static String update_special_icon = baseurl + "update_special_icon";
    public static String add_question_like = baseurl + "add_question_like";
    public static String add_question_flag = baseurl + "add_question_flag";
    public static String search_question = baseurl + "search_question";
    public static String add_answer_like = baseurl + "add_answer_like";
    public static String add_answer_flag = baseurl + "add_answer_flag";
    public static String get_user_profile = baseurl + "get_user_profile";
    public static String update_bio = baseurl + "update_bio";
    public static String update_email = baseurl + "update_email";
    public static String change_password = baseurl + "change_password";
    public static String update_zip = baseurl + "update_zip";
    public static String update_name = baseurl + "update_name";
    public static String follow_user = baseurl + "follow_user";
    public static String un_follow = baseurl + "un_follow";
    public static String get_chats = baseurl + "get_chats";
    public static String get_budz_chats = baseurl + "get_budz_chats";
    public static String get_budz_chats_user = baseurl + "get_budz_chats_user/";
    public static String get_detail_chat = baseurl + "get_detail_chat";
    public static String get_budz_detail_chat = baseurl + "get_budz_detail_chat";
    public static String get_users = baseurl + "get_users";
    public static String send_message = baseurl + "send_message";
    public static String send_budz_message = baseurl + "send_budz_message";
    public static String add_group_message = baseurl + "add_group_message";
    public static String add_image_chat = baseurl + "add_image_chat";
    public static String add_video_chat = baseurl + "add_video_chat";
    public static String search_users = baseurl + "search_users";
    public static String get_groups = baseurl + "get_groups";
    public static String get_all_public_groups = baseurl + "get_all_public_groups";
    public static String get_group_messgaes = baseurl + "get_messgaes";
    public static String add_message_like = baseurl + "add_message_like";
    public static String remove_message_like = baseurl + "remove_message_like";
    public static String add_group = baseurl + "add_group";
    public static String get_tags = baseurl + "get_tags";
    public static String get_all_public_groups_alpha = baseurl + "get_all_public_groups_alpha";
    public static String get_all_public_groups_created = baseurl + "get_all_public_groups_created";
    public static String get_all_gublic_groups_joined = baseurl + "get_all_gublic_groups_joined";
    public static String search_group = baseurl + "search_group";
    public static String join_group = baseurl + "join_group";
    public static String delete_chat = baseurl + "delete_chat";
    public static String delete_chat_budz = baseurl + "delete_chat_budz";
    public static String delete_chat_budzs = baseurl + "delete_chat_budzs";
    public static String logout = baseurl + "logout";
    public static String invite_members = baseurl + "invite_members";
    public static String remove_member = baseurl + "remove_member";
    public static String accept_reject_invitaion = baseurl + "accept_reject_invitaion";
    public static String remove_group = baseurl + "remove_group";
    public static String leave_group = baseurl + "leave_group";
    public static String get_user_groups = baseurl + "get_user_groups";
    //    public static String get_my_question = baseurl + "get_my_question?page_no=0";
    public static String get_my_question = baseurl + "get_my_question";
    //    public static String get_my_answers = baseurl + "get_my_answers?page_no=0";
    public static String get_my_answers = baseurl + "get_my_answers";
    public static String get_all_users = baseurl + "get_all_users?skip=";
    public static String edit_group = baseurl + "edit_group";
    public static String get_my_groups = baseurl + "get_my_groups?page_no=0";
    public static String get_user_profile_strains = baseurl + "get_user_profile_strains";
    public static String create_journal = baseurl + "create_journal";
    public static String add_subscription = baseurl + "add_subscription";
    public static String update_journal = baseurl + "update_journal";
    public static String delete_journal = baseurl + "delete_journal";
    public static String get_user_all_journals = baseurl + "get_user_all_journals";
    public static String get_my_journals_sorting = baseurl + "get_my_journals_sorting";
    public static String get_journal_tags = baseurl + "get_journal_tags";
    public static String get_all_journals = baseurl + "get_all_journals";
    public static String search_journal = baseurl + "search_journal";
    public static String get_journal_events = baseurl + "get_journal_events";
    public static String delete_journal_event = baseurl + "delete_journal_event";
    public static String follow_journal = baseurl + "follow_journal";
    public static String favourtire_journal = baseurl + "favourtire_journal";
    public static String strain_flaged = baseurl + "strain_flaged";
    public static String save_favorit_strain = baseurl + "save_favorit_strain";
    public static String add_group_settings = baseurl + "add_group_settings";
    public static String group_settings = baseurl + "group_settings";
    public static String hb_gallery = baseurl + "hb_gallery";
    public static String block_hb_gallery = baseurl + "block_hb_gallery";//post,param:image_id
    public static String block_user = baseurl + "block_user";//post,param:user_id
    public static String add_event_image = baseurl + "add_event_image";
    public static String add_event_video = baseurl + "add_event_video";
    public static String create_journal_event = baseurl + "create_journal_event";
    public static String journal_like_or_dislike = baseurl + "journal_like_or_dislike";
    public static String strain_like_dislike = baseurl + "strain_like_dislike";
    public static String get_strains = baseurl + "get_strains";
    public static String get_strain = baseurl + "get_strain";
    public static String strain_details_by_name = baseurl + "strain_details_by_name/";
    public static String get_budz = baseurl + "get_budz";
    public static String get_strains_alphabitically = baseurl + "get_strains_alphabitically";
    public static String get_strains_by_type = baseurl + "get_strains_by_type";
    public static String add_strain_review = baseurl + "add_strain_review";
    public static String get_strain_detail = baseurl + "get_strain_detail";
    public static String flag_strain_review = baseurl + "flag_strain_review";
    public static String save_user_strain = baseurl + "save_user_strain";
    public static String get_user_strain = baseurl + "get_user_strains";
    public static String search_strain_name = baseurl + "search_strain_name";
    public static String save_user_strain_like = baseurl + "save_user_strain_like";
    public static String locate_strain_budz = baseurl + "locate_strain_budz";
    public static String save_survey_answer = baseurl + "save_survey_answer";
    public static String search_strain_survey = baseurl + "search_strain_survey";
    public static String delete_question = baseurl + "delete_question";
    public static String delete_answer = baseurl + "delete_answer";
    public static String delete_budz_service = baseurl + "delete_budz_service/";
    public static String delete_budz_ticket = baseurl + "delete_budz_ticket/";
    public static String delete_product = baseurl + "delete_product/";
    public static String delete_hb_gallery = baseurl + "delete_hb_gallery";
    public static String add_shout_out = baseurl + "add_shout_out";
    public static String add_budz_special = baseurl + "add_budz_special";
    public static String get_shout_outs = baseurl + "get_shout_outs";
    public static String shout_detail = baseurl + "shout_detail";
    public static String user_shout_outs = baseurl + "user_shout_outs";
    public static String clear_all_notifications = baseurl + "clear_all_notifications";
    public static String get_notifications = baseurl + "get_notifications";
    public static String filter_my_save = baseurl + "filter_my_save";
    public static String delete_my_save = baseurl + "delete_my_save";
    public static String get_my_strains = baseurl + "get_my_strains";
    public static String delete_user_strain = baseurl + "delete_user_strain";
    public static String get_my_journals_calander = baseurl + "get_my_journals_calander";
    public static String add_journal_reminder_setting = baseurl + "add_journal_reminder_setting";
    public static String get_journal_settings = baseurl + "get_journal_settings";
    public static String get_budz_map = baseurl + "get_budz_map";
    public static String my_get_budz_map = baseurl + "my_budz_map";
    public static String user_my_get_budz_map = baseurl + "get_user_profile_budz_map";
    public static String user_my_get_reviews = baseurl + "get_user_profile_reviews";
    public static String add_listing = baseurl + "add_listing";
    public static String add_logo = baseurl + "add_logo";
    public static String add_banner = baseurl + "add_banner";
    public static String save_favorit_bud = baseurl + "save_favorit_bud";
    public static String save_share = baseurl + "save_share";
    public static String save_budz_menu_click = baseurl + "save_budz_menu_click";
    public static String save_budz_call_click = baseurl + "save_budz_call_click";
    public static String save_budzmap_share = baseurl + "save_budzmap_share";
    public static String save_budz_ticket_click = baseurl + "save_budz_ticket_click";
    public static String get_languages = baseurl + "get_languages";
    public static String get_budz_profile = baseurl + "get_budz_profile";
    public static String add_budz_review = baseurl + "add_budz_review";
    public static String add_budz_review_reply = baseurl + "add_budz_review_reply";
    public static String add_budz_image = baseurl + "add_budz_image";
    public static String add_budz_review_flag = baseurl + "add_budz_review_flag";
    public static String get_all_questions = baseurl + "get_all_questions";
    public static String get_group = baseurl + "get_group";
    public static String get_journal = baseurl + "get_journal";
    public static String get_notification_settings = baseurl + "get_notification_settings";
    public static String remove_tag = baseurl + "remove_tag";
    public static String add_notificarion_setting = baseurl + "add_notificarion_setting";
    public static String follow_keyword = baseurl + "follow_keyword";
    public static String add_journal_setting = baseurl + "add_journal_setting";
    public static String add_journal_data_setting = baseurl + "add_journal_data_setting";
    public static String get_user_strain_detail = baseurl + "get_user_strain_detail";
    public static String get_followings = baseurl + "get_followings";
    public static String get_followers = baseurl + "get_followers";
    public static String delete_special = baseurl + "delete_special";
    public static String like_shout_out = baseurl + "like_shout_out";
    public static String get_sub_users = baseurl + "get_sub_users";
    public static String save_user_image_strain_like = baseurl + "save_user_image_strain_like";
    //    public static String save_user_image_strain_dislike = baseurl + "save_user_image_strain_like";
    public static String save_user_image_strain_dislike = baseurl + "save_user_image_strain_dislike";
    public static String save_user_image_strain_flag = baseurl + "save_user_image_strain_flag";
    public static String suggest_medical_condition = baseurl + "suggest_medical_condition";
    public static String suggest_sensation = baseurl + "suggest_sensation";
    public static String suggest_negative_effect = baseurl + "suggest_negative_effect";
    public static String suggest_disease_prevention = baseurl + "suggest_disease_prevention";
    public static String save_strain_search = baseurl + "save_strain_search";
    public static String delete_strain_review = baseurl + "delete_strain_review";
    public static String delete_budz_review = baseurl + "delete_budz_review";
    public static String delete_budz_review_reply = baseurl + "delete_budz_review_reply";
    public static String delete_sub_user = baseurl + "delete_sub_user";
    //REWARDZ
    public static final String get_my_rewards = baseurl + "get_my_rewards";
    public static final String get_products = baseurl + "get_products";
    public static final String get_user_point_log = baseurl + "get_user_point_log";
    public static final String purchase_product = baseurl + "purchase_product";
    //Muzammil Android Branch
    public static final String addPostImageURL = baseurl + "add_post_image";
    public static final String addPostVideoURL = baseurl + "add_post_video";
    public static String save_favorit_shout_out = baseurl + "save_favorit_shout_out";
    public static String job_remaind_later = baseurl + "job_remaind_later";
    public static String add_expertise_suggestion = baseurl + "add_expertise_suggestion";
    public static String change_show_ads_status = baseurl + "change_show_ads_status";
    public static String get_budz_chat_detail = baseurl + "get_budz_chat_detail";
    public static String add_budz_flag = baseurl + "add_budz_flag";
    public static String share_post_in_app = baseurl + "share_post_in_app";
    public static String add_strain_review_like = baseurl + "add_strain_review_like";
    public static String add_budz_review_like = baseurl + "add_budz_review_like";
    public static String get_edits = baseurl + "get_edits/";
    public static String save_chat = baseurl + "save_chat";
    public static String save_chat_budz = baseurl + "save_chat_budz";
    public static String get_chat_detail_by_id = baseurl + "get_chat_detail_by_id/";
    public static String add_budz_product_image = baseurl + "add_budz_product_image";
    public static String add_budz_product = baseurl + "add_budz_product";
    public static String add_budz_service = baseurl + "add_budz_service";
    public static String add_budz_ticket = baseurl + "add_budz_ticket";
    public static String delete_strain_image = baseurl + "delete_strain_image/";


    //    public static String getPostUrl(int postId) {
//        return "Hey Bud! Check out the Healing Budz app for your smart phone.” Download it today from  http://" + IP_SERVER + "/" + PROJECT_NAME + "/get-post/" + String.valueOf(postId);
//    }

    //Muzammil Android Branch
}

